-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.util.** { *; }
-keepattributes *Annotation*
-dontwarn androidx.**
-dontwarn io.flutter.**
